kind: Service
apiVersion: v1
metadata:
  name: basket-svc
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket
  labels:
    app: basket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket
  template:
    metadata:
      labels:
        app: basket
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "basket-svc"
        dapr.io/port: "3000"
    spec:
      containers:
      - name: basket
        image: lgmorand/eshop-basket
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
