apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: basket-statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    value: VlZjNWJ6SmhSV2xvWnc9PQ==
