kind: Service
apiVersion: v1
metadata:
  name: website
  labels:
    app: website
spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "website"
        dapr.io/port: "80"
    spec:
      containers:
      - name: website
        image: lgmorand/eshop-website
        ports:
        - containerPort: 80
        imagePullPolicy: Always
