apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "payment-app"
        dapr.io/port: "80"
    spec:
      containers:
      - name: payment
        image: lgmorand/eshop-payment
        ports:
        - containerPort: 80
        imagePullPolicy: Always
