name: Build eshop.payment image

on:
  push:
    paths:
      - '**/eshop.payment/**'
      - '**build-payment.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: lgmorand/eshop-payment
        tags: latest
        dockerfile: src/eshop.payment/Dockerfile
        path: src
    