name: Build eshop.order image

on:
  push:
    paths:
      - '**/eshop.order/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: lgmorand/eshop-order
        tags: latest
        dockerfile: src/eshop.order/Dockerfile
    