name: Build eshop.basket image

on:
  push:
    paths:
      - '**/eshop.basket/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: lgmorand/eshop-basket
        tags: latest
        dockerfile: src/eshop.basket/Dockerfile
        path: src
    